load("@fbsource//tools/build_defs/android:fb_android_binary.bzl", "fb_android_binary")
load("@fbsource//tools/build_defs/android:fb_android_library.bzl", "fb_android_library")
load("@fbsource//tools/build_defs/android:fb_android_resource.bzl", "fb_android_resource")

oncall("executorch")

fb_android_resource(
    name = "app_res",
    package = "com.example.medoffline",
    res = "res",
)

fb_android_library(
    name = "app_lib",
    srcs = [
        "java/com/example/medoffline/AppLog.java",
        "java/com/example/medoffline/BackendType.java",
        "java/com/example/medoffline/DemoSharedPreferences.java",
        "java/com/example/medoffline/ETImage.java",
        "java/com/example/medoffline/ETLogging.java",
        "java/com/example/medoffline/LlmBenchmarkRunner.java",
        "java/com/example/medoffline/LogsActivity.java",
        "java/com/example/medoffline/LogsAdapter.java",
        "java/com/example/medoffline/MainActivity.java",
        "java/com/example/medoffline/Message.java",
        "java/com/example/medoffline/MessageAdapter.java",
        "java/com/example/medoffline/MessageType.java",
        "java/com/example/medoffline/ModelRunner.java",
        "java/com/example/medoffline/ModelRunnerCallback.java",
        "java/com/example/medoffline/ModelType.java",
        "java/com/example/medoffline/ModelUtils.java",
        "java/com/example/medoffline/PromptFormat.java",
        "java/com/example/medoffline/SettingsActivity.java",
        "java/com/example/medoffline/SettingsFields.java",
    ],
    autoglob = False,
    language = "JAVA",
    deps = [
        ":app_res",
        "//third-party/java/androidx/constraintlayout/constraintlayout:constraintlayout",
        "//third-party/java/com/google/code/gson/gson:gson",
        "//xplat/executorch/extension/android:executorch_llama",
    ],
)

fb_android_binary(
    name = "MedOffLine",
    keystore = "//fbandroid/keystores:debug",
    manifest = "AndroidManifest.xml",
    manifest_entries = {
        "min_sdk_version": 21,
        "target_sdk_version": 34,
        "version_code": "1",
        "version_name": "0.0.3",
    },
    package_type = "release",
    skip_proguard = True,
    deps = [
        ":app_lib",
        ":app_res",
        "//third-party/java/androidx/appcompat/appcompat:appcompat",
        "//third-party/java/com/google/code/gson/gson:gson",
        "//xplat/executorch/extension/android:executorch_llama",
        "//xplat/executorch/extension/android/jni:executorch_llama_jni",
    ],
)
